name: 'Continuous Delivery'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Solo ejecutar el paso de build y push cuando sea desde la rama main
      - name: Build and push
        if: github.ref == 'refs/heads/main'  
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nicolaszagu/lmlatam:latest

      # Solo ejecutar el paso de build y push a otro tag cuando no sea desde la rama main
      - name: Build and push
        if: github.ref != 'refs/heads/main'  
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nicolaszagu/lmlatam:test