name: 'Continuous Delivery'

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.head_ref }}

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUDSECRET }}'

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker

      # Construir y subir la imagen de Docker a Google Container Registry (latest)
      - name: Build and push Docker image to Google Container Registry (latest)
        if: (github.ref == 'refs/heads/main' || github.base_ref == 'main') && github.event_name == 'workflow_dispatch'
        run: |
          docker build -t gcr.io/lmlatam/mllatam:latest .
          docker push gcr.io/lmlatam/mllatam:latest

      # Construir y subir la imagen de Docker a Google Container Registry (test)
      - name: Build and push Docker image to Google Container Registry (test)
        if: (github.ref == 'refs/heads/develop' || github.base_ref == 'develop') && (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch')
        run: |
          docker build -t gcr.io/lmlatam/mllatam:test .
          docker push gcr.io/lmlatam/mllatam:test

  gcloud-upload:
    runs-on: ubuntu-latest
    needs: build-and-push-docker 
    environment: production
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.head_ref }}

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUDSECRET }}'
          token_format: 'access_token'

      - name: Deploy to Cloud Run (latest)
        id: deploy-latest
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: mllatam
          image: gcr.io/lmlatam/mllatam:latest